### ISSUE TITLE
Girl Meets Rock more like publoader meets chaos

### ISSUE THREAD

**Issue by curche** [ArdaxHz/publoader-extensions#48] opened 2024-02-17 18:55 UTC
1. "001-004" - Ch 1-4
2. "005-007" - Ch 5-7
3. "008" - Ch 8

I thought [0fe66c](https://github.com/ArdaxHz/publoader-extensions/commit/0fe66c26eeb7f280f4606d000d041618e1a15096) would have worked but turns out it hasnt /shrug

https://mangadex.org/title/7b727ae2-2842-4c46-af8b-9162b7806659/girl-meets-rock

**Comment by ArdaxHz** [comment] 2024-03-09 00:51
Checked on local, it's working as intended, closing.

**Closed by ArdaxHz** 2024-03-09 00:51 UTC
